services:
  db:
    image: postgres:15-alpine
    container_name: url_shortener_db
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shortener_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:7-alpine
    container_name: url_shortener_cache
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data: